apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-boot-k8s-configmap
data:
  application.properties: |
    kr.co.manty.author=MantyK8s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-boot-k8s
  name: spring-boot-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-k8s
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - image: localhost:32000/spring-boot-k8s
          name: spring-boot-k8s
          volumeMounts:
            - name: application-properties
              mountPath: /workspace/config
              readOnly: true
      volumes:
        - name: application-properties
          configMap:
            name: spring-boot-k8s-configmap
            items:
            - key: "application.properties"
              path: "application.properties"


